### ISSUE TITLE
Runner script might open non-existent coverage file

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd-compiler-testing#9]
The runner script for regression might crash with error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/llvm-regression-tests-runner", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/dredd-compiler-testing/dredd_test_runners/llvm_regression_tests_runner/main.py", line 148, in main
    open(dredd_covered_mutants_path, 'r').readlines()]))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8npapj50/__dredd_covered_mutants'
```

I believe this happens because `dredd` with mutant_tracking won't create a new file when there's no covered mutant.

**Comment by afd** [comment]
Thanks - are you able to push a fix? I guess check whether the file exists, and continue the loop if it does not.
